// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: transaction.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class Data;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - TransactionRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface TransactionRoot : GPBRootObject
@end

#pragma mark - Data

typedef GPB_ENUM(Data_FieldNumber) {
  Data_FieldNumber_Type = 1,
  Data_FieldNumber_Payload = 2,
};

@interface Data : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *type;

@property(nonatomic, readwrite, copy, null_resettable) NSData *payload;

@end

#pragma mark - Transaction

typedef GPB_ENUM(Transaction_FieldNumber) {
  Transaction_FieldNumber_Hash_p = 1,
  Transaction_FieldNumber_From = 2,
  Transaction_FieldNumber_To = 3,
  Transaction_FieldNumber_Value = 4,
  Transaction_FieldNumber_Nonce = 5,
  Transaction_FieldNumber_Timestamp = 6,
  Transaction_FieldNumber_Data_p = 7,
  Transaction_FieldNumber_ChainId = 8,
  Transaction_FieldNumber_GasPrice = 9,
  Transaction_FieldNumber_GasLimit = 10,
  Transaction_FieldNumber_Alg = 11,
  Transaction_FieldNumber_Sign = 12,
};

@interface Transaction : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSData *hash_p;

@property(nonatomic, readwrite, copy, null_resettable) NSData *from;

@property(nonatomic, readwrite, copy, null_resettable) NSData *to;

@property(nonatomic, readwrite, copy, null_resettable) NSData *value;

@property(nonatomic, readwrite) uint64_t nonce;

@property(nonatomic, readwrite) int64_t timestamp;

@property(nonatomic, readwrite, strong, null_resettable) Data *data_p;
/** Test to see if @c data_p has been set. */
@property(nonatomic, readwrite) BOOL hasData_p;

@property(nonatomic, readwrite) uint32_t chainId;

@property(nonatomic, readwrite, copy, null_resettable) NSData *gasPrice;

@property(nonatomic, readwrite, copy, null_resettable) NSData *gasLimit;

@property(nonatomic, readwrite) uint32_t alg;

@property(nonatomic, readwrite, copy, null_resettable) NSData *sign;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
